name: opam

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Pin Z3 to system version
        run: opam pin add z3.system -k version 4.12.2  --no-depexts
  
      - name: Set up opam environment
        run: opam install dune opam-depext z3 menhir zarith num --no-depexts

      - name: Build
        run: opam exec -- dune build

      - name: Run program
        run: opam exec -- dune exec laurent banner
