name: opam

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ocaml-version:
          - 4.14.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      
      - name: Fix apt sources
        run: sudo apt-get update --fix-missing

      - run: eval $(opam env) 
      - run: opam exec -- dune build
      
